changelog:
  categories:
    - title: Feature
      labels:
        - type:Feature
    - title: Bugfix
      labels:
        - [type:Bugfix, type:Hotfix]
    - title: Other Changes
      labels:
        - "type:Task"
