changelog:
  categories:
    - title: Feature
      labels:
        - type:Feature
    - title: Bugfix
      labels:
        - type:Bugfix
    - title: Other Changes
      labels:
        - "type:Task"
