name: GitHub Release

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Extract tag name
        id: extract_tag_name
        run: |
          if [[ ${{ github.head_ref }} =~ release\/(v[0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            echo "tag_name=${BASH_REMATCH[1]}" >> "$GITHUB_OUTPUT"
          else
            echo "No semantic version found in branch name."
          fi
      - name: Push tag
        uses: mathieudutour/github-tag-action@fcfbdceb3093f6d85a3b194740f8c6cec632f4e2 # v6.1
        if: github.event.pull_request.merged == true && steps.extract_tag_name.outputs.tag_name != ''
        id: push_tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.extract_tag_name.outputs.tag_name }}
          tag_prefix: ""
      - name: Create release
        uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5 # v1.14.0
        if: github.event.pull_request.merged == true && steps.extract_tag_name.outputs.tag_name != ''
        with:
          tag: ${{ steps.push_tag.outputs.new_tag }}
          name: ${{ steps.push_tag.outputs.new_tag }}
          generateReleaseNotes: true
