name: Required PR Labels for Main

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, labeled, unlabeled, review_requested, ready_for_review]

jobs:
  label:
    runs-on: ubuntu-22.04
    steps:
      - name: Check required labels
        env:
          LABELS: ${{ toJson(github.event.pull_request.labels.*.name) }}
        run: |
          required_labels_length=$(echo "${LABELS}" | jq 'map(select(. | contains("type:Release"))) | length')
          if [[ ${required_labels_length} -ne 1 ]]; then
            echo "Pull request must have the following label: type:Release."
            exit 1
          fi    
